#ifndef   _INPUT_H
#define   _INPUT_H





int RegisteraccountsInput(char *accounts, int *mx, int *my);
int RegistercodeInput(char *code, int *mx, int *my);
int RegistersecondcodeInput(char *secondcode, int *mx, int *my);
int  searchInput(char *abbreviation, int *mx, int *my);
int oldcodeinput(char *code, int *mx, int *my);
int newcodeinput(char *code, int *mx, int *my);
int secondcodeinput(char *code, int *mx, int *my);

#endif
